# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Module-Checkstyle
version:      0.02
version_from: lib/Module/Checkstyle.pm
installdirs:  site
requires:
    Carp:                          0
    Config::Tiny:                  0
    File::Find::Rule:              0
    File::HomeDir:                 0
    File::Spec:                    0
    Getopt::Long:                  0
    List::Util:                    0
    Pod::Usage:                    0
    PPI:                           1
    Readonly:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
